### PR TITLE
Expose Binary type in smt2 driver and python API

### PR DESCRIPTION
**Pull request by em-mcg**
I went through the building and testing steps in `CONTRIBUTING.md`.

---
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal4/115)

### CODE REVIEW

**Comment by em-mcg** [comment]
I used dReal for a project encoding floats as arrays of Type::Binary Variables, and using the Binary type led to a significant speedup over implementations using Integer or Boolean. When I tried using Integers constrained to be 0 or 1 or Boolean variables, I never saw the solver finish, but when I switched to Binary, the sat formula I'd been trying to solve finished in less than a second.

**Comment by soonho-tri** [comment]
Good to know.

:lgtm:

**Comment by em-mcg** [comment]
Do I need to do something about the codecov results before this can be merged?

**Comment by soonho-tri** [comment]
> Do I need to do something about the codecov results before this can be merged?

Not a problem. Just merged.

**Comment by soonho-tri** [comment]
>  When I tried using Integers constrained to be 0 or 1 or Boolean variables, I never saw the solver finish, but when I switched to Binary, the sat formula I'd been trying to solve finished in less than a second.

BTW, can you share the smt2 files with me?

**Pull request merged**
