### PR TITLE
Implement (let) using globals with unique names

### PR DESCRIPTION
**Pull request by martinjos**
Related issue: #5

This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal4/64)

### CODE REVIEW

**Comment by soonho-tri** [comment]
First pass completed. Please take a look.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dreal/smt2/driver.cc, line 70 at r1](https://reviewable.io:443/reviews/dreal/dreal4/64#-L88pG4L09C923S-HaZE:-L88pG4L09C923S-HaZF:b-g2r63j) ([raw file](https://github.com/dreal/dreal4/blob/de8ed286e6ad766e3521330454900fec4db0cb58/dreal/smt2/driver.cc#L70)):*
> ```cpp
> }
> 
> Variable Smt2Driver::RegisterVariable(const std::string& name, Sort sort) {
> ```

BTW, nit, as we have `using std::string;` at the beginning of this file, all occurrences of `std::string` can be reduced to `string`.

---

*[dreal/smt2/driver.cc, line 94 at r1](https://reviewable.io:443/reviews/dreal/dreal4/64#-L88pZL5rVFPRkBy41QU:-L88pZL5rVFPRkBy41QV:b-6xzpt6) ([raw file](https://github.com/dreal/dreal4/blob/de8ed286e6ad766e3521330454900fec4db0cb58/dreal/smt2/driver.cc#L94)):*
> ```cpp
> }
> 
> Variable Smt2Driver::DeclareLocalVariable(const std::string& name, Sort sort) {
> ```

BTW, nit, in `.cpp` file, we prefer `const Sort sort` over `Sort sort`.

---

*[dreal/smt2/driver.h, line 75 at r1](https://reviewable.io:443/reviews/dreal/dreal4/64#-L88tCKetQmlmKKXSVlm:-L88tCKetQmlmKKXSVln:b-1p8noq) ([raw file](https://github.com/dreal/dreal4/blob/de8ed286e6ad766e3521330454900fec4db0cb58/dreal/smt2/driver.h#L75)):*
> ```objc
>                        const Term& lb, const Term& ub);
> 
>   /// Declare a new variable with label @p name that is globally unique and
> ```

As you may know, `Variable` is identified by its `ID`, not by its `name`. I'm wondering if we need to make an effort to make a globally unique name for local variables.

---

*[dreal/smt2/parser.yy, line 516 at r1](https://reviewable.io:443/reviews/dreal/dreal4/64#-L88tXso8a_FptOXoolp:-L88tXso8a_FptOXoolq:b-l8s8wf) ([raw file](https://github.com/dreal/dreal4/blob/de8ed286e6ad766e3521330454900fec4db0cb58/dreal/smt2/parser.yy#L516)):*
> ```Yacc
>                     driver.context_.Assert(Expression{v} == term.expression());
>                 }
>             }
> ```

FYI, we want to use `const` as many as possible:
```c++
            for (const auto& binding : *$2) {
                const std::string& name{binding.first};
                const Term& term{binding.second};
                const bool is_formula = term.type() == Term::Type::FORMULA;
                const Sort sort = is_formula ? Sort::Bool : Sort::Real;
                const Variable v{driver.DeclareLocalVariable(name, sort)};
                if (is_formula) {
                    const Formula fv{v};
                    const Formula& ft{term.formula()};
                    driver.context_.Assert((fv && ft) || (!fv && !ft));
                } else {
                    driver.context_.Assert(Expression{v} == term.expression());
                }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dreal/dreal4/64#-:-L88tiavbh8W5i_6ksLL:bjd9556)*

**Comment by martinjos** [comment]
I did not know that a `Variable` is not identified by its name. However, after parsing, the details of any `let` constructs will be lost.  So I think it's a good idea to have different names so that the user can still make sense of debug messages, etc. (It also means that we can in principle reconstruct the details of the `let` constructs if necessary.)

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[dreal/smt2/driver.h, line 75 at r1](https://reviewable.io:443/reviews/dreal/dreal4/64#-L88tCKetQmlmKKXSVlm:-L8I5CWvVnO8ioQ2BXvv:b4wlntu) ([raw file](https://github.com/dreal/dreal4/blob/de8ed286e6ad766e3521330454900fec4db0cb58/dreal/smt2/driver.h#L75)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

As you may know, `Variable` is identified by its `ID`, not by its `name`. I'm wondering if we need to make an effort to make a globally unique name for local variables.
</blockquote></details>

OK. Withdrawn this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dreal/dreal4/64)*

**Comment by soonho-tri** [comment]
BTW, it'd be way easier if you read my comments via https://reviewable.io/reviews/dreal/dreal4/64

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dreal/dreal4/64#-:-L8I7wkSx1lg-O0PhpDm:bnfp4nl)*

**Pull request merged**
