### PR TITLE
Add missing logic

### LINKED ISSUE #274: Missing logic
We can handle `QF_LIA`, `QF_LIRA`, `QF_NIA`, and `QF_NIRA`. But dReal throws an exception when it detects those logic.

### PR DESCRIPTION
**Pull request by soonhokong**
Close #274

---
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal4/276)

### CODE REVIEW

**Comment by soonhokong** [comment]
+@yazhai

**Review by soonhokong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dreal/dreal4/276)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yazhai)

___
*[`dreal/smt2/logic.h` line 25 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7Wd-8ICN4g6iGA5bDx:-N7Wd-8ICN4g6iGA5bDy:b5uynkm) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.h#L25)):*
> ```objc
> enum class Logic {
>   ALL,
>   QF_LIA,
> ```

What's this?
___
*[`dreal/smt2/logic.cc` line 39 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7WdFVrEme7B7TJuUsA:-N7WdFVrEme7B7TJuUsB:bzf5mxu) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.cc#L39)):*
> ```cpp
>   }
>   if (s == "QF_LIRA") {
>     return Logic::QF_LIRA;
> ```

Can you explain this?

**Review by yazhai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dreal/dreal4/276)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @soonhokong and @yazhai)

___
*[`dreal/smt2/logic.h` line 25 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7Wd3F3-svPOstJ7Zpy:-N7Wd3F3-svPOstJ7Zpz:b-97wgmt) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.h#L25)):*
> ```objc
> enum class Logic {
>   ALL,
>   QF_LIA,
> ```

Here is my test comment 1
___
*[`dreal/smt2/logic.cc` line 39 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7WdFVrEme7B7TJuUsA:-N7WdO3xCHBadLc5zZAH:b-t83fld) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.cc#L39)):*
<details><summary><i>Previously, soonhokong (Soonho Kong) wrote…</i></summary><blockquote>

Can you explain this?
</blockquote></details>

This is my reply
___
*[`dreal/smt2/logic.cc` line 65 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7WdCE11gqxxkwXChUf:-N7WdCE11gqxxkwXChUg:bq5w11l) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.cc#L65)):*
> ```cpp
>       return os << "QF_NIRA";
>     case Logic::QF_NRA:
>       return os << "QF_NRA";
> ```

This is a test comment  No.2 from Yaoguang

**Review by soonhokong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dreal/dreal4/276)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @yazhai)

___
*[`dreal/smt2/logic.h` line 25 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7Wd3F3-svPOstJ7Zpy:-N7WdbRZ4ZP-NmID4MNf:b-896fix) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.h#L25)):*
<details><summary><i>Previously, yazhai (Yaoguang Zhai) wrote…</i></summary><blockquote>

Here is my test comment 1
</blockquote></details>

Done.
___
*[`dreal/smt2/logic.cc` line 65 at r1](https://reviewable.io/reviews/dreal/dreal4/276#-N7WdCE11gqxxkwXChUf:-N7WdaXg6DDLxZccBFIo:b-896fix) ([raw file](https://github.com/dreal/dreal4/blob/28062dab1447cb7d6f2ffe38d6c170b5d33c0004/dreal/smt2/logic.cc#L65)):*
<details><summary><i>Previously, yazhai (Yaoguang Zhai) wrote…</i></summary><blockquote>

This is a test comment  No.2 from Yaoguang
</blockquote></details>

Done.

**Review by yazhai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dreal/dreal4/276)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @yazhai)

**Review by yazhai — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dreal/dreal4/276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @soonhokong)

**Review by yazhai — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dreal/dreal4/276#-:-N7WeA3q9eVZPocambvo:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @soonhokong)

**Pull request merged**
