### PR TITLE
fix: Check errors when parsing numbers

### PR DESCRIPTION
**Pull request by martinjos**
`atoi` and `atof` do not check errors: if the input is too large, the result is undefined.

`strtol` and `strtod` are the recommended replacements: if the input is too large, they return `LONG_MIN`/`LONG_MAX` and +/-`HUGE_VAL`, respectively.

Wrapper functions `strtol_checked` and `strtod_checked` call `DREAL_RUNTIME_ERROR` if they get these values, or if parsing fails in some other way.

As strtol is defined to return `long`, I have had to disable the `runtime/int` check in `CPPLINT.cfg` to suppress warnings about the use of this type. Hopefully this should not be too much of an issue.

There seems to be no particular obstacle to the use of `long` instead of `int` for `INT`/`intVal`, apart from the lint warning. On 64-bit platforms, `int` is typically 32-bit and `long` is typically 64-bit. I don't think it's appropriate in this case to use `int64` because on some systems `long` might not be `int64` (e.g. on 32-bit systems it is usually `int32`, but it could hypothetically be something larger).

It is difficult to test this change, as the test script `dreal/test/smt2/test.py` does not currently allow tests to throw exceptions. Ideally, it should validate the exceptions using an extra field to `smt2_test()`.

For this reason, I have had to disable `dreal/test/smt2/fabian_01.smt2`, as it now throws an exception because of a number that is too large.

---
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal4/59)

### CODE REVIEW

**Comment by soonho-tri** [comment]
First of all, thanks for the contribution!

> As strtol is defined to return long, I have had to disable the runtime/int check in CPPLINT.cfg to suppress warnings about the use of this type. Hopefully this should not be too much of an issue.

I'd like to suggest to change `long strtol_checked` to `int strtoi_checked`. Here is why: With the following assumptions,
 -  `int` is 32-bit long
 - `long` is 64-bit long
 - `double` is 64-bit long
an int value can be represented with a `double` variable precisely because `double` has 53-bit precision which is enough to represent a `32-bit` value. This is an important property for us since we use a `double` interval to represent both of integer and real values internally.

**Comment by martinjos** [comment]
That's a very good point about the precisions of `long` and `double`. I know that it gets converted immediately into `double` when it's parsed as part of an expression.

Converting to `int` would be an adequate solution, provided that we first ensure that the number is in `[INT_MIN, INT_MAX]`. However, there is another option, which is to parse it as a `double`, and then restrict to the maximum unambiguous integer range. This is `[-(2**53 - 1), 2**53 - 1]`. (`2**53` is ambiguous because `2**53+1` gets rounded down, but `2**53-1` is unambiguous.)

**Comment by soonho-tri** [comment]
How about using `std::stoi` which does the job for us? It takes `std::string` but `std::string` has a constructor taking `const char*`. So we should be able to use it immediately.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dreal/dreal4/59#-:-L7Bs8P1Sy4MYUnEHn6O:b-7sqi8x)*

**Comment by martinjos** [comment]
I guess `stoi` would work for ints, but not for doubles. Also, it wouldn't preserve 53 bits of precision. See PR #60 (which has one extra commit on top of this one).

**Comment by martinjos** [comment]
Okay, I'm willing to go with whatever you think it best. Either solution will work for me.

**Comment by soonho-tri** [comment]
FYI, you can push the new commits to your `number-parse-checks` branch then Github will update this PR automatically. Can you test it (by closing #60)?

**Comment by martinjos** [comment]
Yes, I knew I could do that - I just didn't know whether you would like my solution. :-)

**Comment by martinjos** [comment]
I've just realised that this could also be built on top of `std::stof`

**Pull request closed without merging**
